### ISSUE TITLE
Preset kills audio until reload

### ISSUE THREAD

**Issue by knobster** [the-synister/the-builds#2]
playing the following sound for a couple of seconds kills the plugin's audio output until the plugin or project is reloaded in daw:

[shroom phone.xml.zip](https://github.com/the-synister/synister/files/188694/shroom.phone.xml.zip)

problematic parameter not identified yet. might be related to the filter (resonance), clipping or bit reduction. 

os: x (el captain), ableton 9.6

**Comment by knobster** [comment]
seems to be the bandpass (cutoff frequencies colliding during heavy modulation?)

**Comment by juanecabellob** [comment]
let's keep all the bugs on the-synister/the-source repository for consistency.
I'm adding this bug to that repository and closing this one.
